_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.11.10
        t:
            "1":
                - 1
                - 2
                - 3
                - 49
                - 55
                - 105
            "2":
                - 1
                - 2
                - 3
                - 49
                - 55
                - 105
            "3":
                - 15
                - 16
                - 23
                - 55
            "4": 3.11.10
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
conv_filters:
    value:
        - 64
        - 32
        - 16
        - 8
        - 4
dense_channels:
    value: 24
kernel_size:
    value: 11,11
latent_size:
    value: 96
